spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: idyllo
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: select 'x'
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  jpa:
    show-sql: true
# rabbitmq:
#   addresses: 47.106.84.237
#   port: 5762
#   username: admin
#   password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
girl:
  name: azul
  age: 19
